// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"cjg4kq6m3l","name":"sampleCloudApi","description":"","endpoint":"https://cjg4kq6m3l.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:75b02d14-0827-44c2-89db-7061895457fc',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'ubiqdisplays-hosting-mobilehub-1718682516',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dwicr2xcfuepk.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"ubiqdisplays-mobilehub-1718682516-AWSMobileTable","attributes":[{"name":"teamId","type":"S"},{"name":"personId","type":"S"},{"name":"email","type":"S"},{"name":"personName","type":"S"},{"name":"phone","type":"S"}],"indexes":[{"indexName":"personName-index","hashKey":"teamId","rangeKey":"personName"}],"region":"us-east-1","hashKey":"teamId","rangeKey":"personId"}],
    'aws_mobile_analytics_app_id': '6bf7dcafc5404c0bb247e46a163c94dc',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '1a54b823-e02f-42e5-ac45-f4b121bf4d1c',
    'aws_project_name': 'ubiq-displays3-2018-06-06-11-09-14',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'ubiqdisplays-deployments-mobilehub-1718682516',
    'aws_resource_name_prefix': 'ubiqdisplays-mobilehub-1718682516',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_uF1LFVWMw',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': 'p6nth95n3pcbugn26s8p8ubh2',
}

export default awsmobile;
